In [11]:
import sys

In [12]:
!{sys.executable} -m pip uninstall -y numpy pandas pandas-datareader
!{sys.executable} -m pip install numpy==1.23.5 pandas==1.5.3 pandas-datareader==0.10.0

Found existing installation: numpy 2.2.6
Uninstalling numpy-2.2.6:
  Successfully uninstalled numpy-2.2.6
Found existing installation: pandas 1.5.3
Uninstalling pandas-1.5.3:
  Successfully uninstalled pandas-1.5.3
Found existing installation: pandas-datareader 0.10.0
Uninstalling pandas-datareader-0.10.0:
  Successfully uninstalled pandas-datareader-0.10.0
Collecting numpy==1.23.5
  Downloading numpy-1.23.5-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (17.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 17.1/17.1 MB 446.4 kB/s eta 0:00:0000:0100:01
Collecting pandas==1.5.3
  Using cached pandas-1.5.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (12.1 MB)
Collecting pandas-datareader==0.10.0
  Using cached pandas_datareader-0.10.0-py3-none-any.whl (109 kB)
Requirement already satisfied: pytz>=2020.1 in /home/ankita/.pyenv/versions/3.10.12/lib/python3.10/site-packages (from pandas==1.5.3) (2025.2)
Requirement already satisfied: python-dateutil>=2.8.1 in /home/ankita/.pyenv/versions/3.10.12/lib/python3.10/site-packages (from pandas==1.5.3) (2.9.0.post0)
Requirement already satisfied: lxml in /home/ankita/.pyenv/versions/3.10.12/lib/python3.10/site-packages (from pandas-datareader==0.10.0) (6.0.2)
Requirement already satisfied: requests>=2.19.0 in /home/ankita/.pyenv/versions/3.10.12/lib/python3.10/site-packages (from pandas-datareader==0.10.0) (2.32.5)
Requirement already satisfied: six>=1.5 in /home/ankita/.pyenv/versions/3.10.12/lib/python3.10/site-packages (from python-dateutil>=2.8.1->pandas==1.5.3) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /home/ankita/.pyenv/versions/3.10.12/lib/python3.10/site-packages (from requests>=2.19.0->pandas-datareader==0.10.0) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /home/ankita/.pyenv/versions/3.10.12/lib/python3.10/site-packages (from requests>=2.19.0->pandas-datareader==0.10.0) (3.11)
Requirement already satisfied: certifi>=2017.4.17 in /home/ankita/.pyenv/versions/3.10.12/lib/python3.10/site-packages (from requests>=2.19.0->pandas-datareader==0.10.0) (2025.11.12)
Requirement already satisfied: urllib3<3,>=1.21.1 in /home/ankita/.pyenv/versions/3.10.12/lib/python3.10/site-packages (from requests>=2.19.0->pandas-datareader==0.10.0) (2.6.2)
Installing collected packages: numpy, pandas, pandas-datareader
Successfully installed numpy-1.23.5 pandas-1.5.3 pandas-datareader-0.10.0

[notice] A new release of pip is available: 23.0.1 -> 26.0.1
[notice] To update, run: pip install --upgrade pip

In [1]:
import numpy as np
import pandas as pd

print(np.__version__)
print(pd.__version__)

1.23.5
1.5.3

In [2]:
import pandas_datareader as pdr
key="1877dbb9a56522ba7345ad7a1a9c26e2118f6894"

In [3]:
df = pdr.get_data_tiingo("GOOG", api_key=key)

/tmp/ipykernel_29584/2103459282.py:1: FutureWarning: In a future version of pandas all arguments of concat except for the argument 'objs' will be keyword-only.
  df = pdr.get_data_tiingo("GOOG", api_key=key)

In [4]:

df.head()

                                    close       high      low     open  \
symbol date
GOOG   2021-02-08 00:00:00+00:00  2092.91  2123.5469  2072.00  2105.91
       2021-02-09 00:00:00+00:00  2083.51  2105.1300  2078.54  2078.54
       2021-02-10 00:00:00+00:00  2095.38  2108.3700  2063.09  2094.21
       2021-02-11 00:00:00+00:00  2095.89  2102.0300  2077.32  2099.51
       2021-02-12 00:00:00+00:00  2104.11  2108.8200  2083.13  2090.25

                                   volume    adjClose     adjHigh      adjLow  \
symbol date
GOOG   2021-02-08 00:00:00+00:00  1242411  103.860109  105.380457  102.822456
       2021-02-09 00:00:00+00:00   886247  103.393637  104.466523  103.147002
       2021-02-10 00:00:00+00:00  1132741  103.982682  104.627308  102.380299
       2021-02-11 00:00:00+00:00   945650  104.007991  104.312687  103.086459
       2021-02-12 00:00:00+00:00   855865  104.415906  104.649639  103.374779

                                     adjOpen  adjVolume  divCash  splitFactor
symbol date
GOOG   2021-02-08 00:00:00+00:00  104.505231   24848220      0.0          1.0
       2021-02-09 00:00:00+00:00  103.147002   17724940      0.0          1.0
       2021-02-10 00:00:00+00:00  103.924621   22654820      0.0          1.0
       2021-02-11 00:00:00+00:00  104.187632   18913000      0.0          1.0
       2021-02-12 00:00:00+00:00  103.728107   17117300      0.0          1.0

In [5]:
df.to_csv('GOOGLE.csv')

In [6]:
import pandas as pd
df=pd.read_csv('GOOGLE.csv')
df.head()

,symbol,date,close,high,low,open,volume,adjClose,adjHigh,adjLow,adjOpen,adjVolume,divCash,splitFactor
0,GOOG,2021-02-08 00:00:00+00:00,2092.91,2123.5469,2072.00,2105.91,1242411,103.860109,105.380457,102.822456,104.505231,24848220,0.0,1.0
1,GOOG,2021-02-09 00:00:00+00:00,2083.51,2105.1300,2078.54,2078.54,886247,103.393637,104.466523,103.147002,103.147002,17724940,0.0,1.0
2,GOOG,2021-02-10 00:00:00+00:00,2095.38,2108.3700,2063.09,2094.21,1132741,103.982682,104.627308,102.380299,103.924621,22654820,0.0,1.0
3,GOOG,2021-02-11 00:00:00+00:00,2095.89,2102.0300,2077.32,2099.51,945650,104.007991,104.312687,103.086459,104.187632,18913000,0.0,1.0
4,GOOG,2021-02-12 00:00:00+00:00,2104.11,2108.8200,2083.13,2090.25,855865,104.415906,104.649639,103.374779,103.728107,17117300,0.0,1.0